version: "3.8"
services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Cuentas 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - backend

  backend:
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy 
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/Cuentas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
volumes:
  mysql_data:
networks:
  backend:
    driver: bridge